baseURL = "https://www.ourmaninindia.com/"
languageCode = "en-us"
title = "Our Man in India"
# No theme line needed!

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[taxonomies]
  category = "categories"
  tag = "tags"

[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

  [outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menus.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  
  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 3
  
  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[[menus.main]]
    name = "Search"
    url = "/search/"
    weight = 5